fix grep error in readme and workflow

diff --git a/.github/workflows/simple-ci-cd.yml b/.github/workflows/simple-ci-cd.yml
--- a/.github/workflows/simple-ci-cd.yml
+++ b/.github/workflows/simple-ci-cd.yml
@@ -64,18 +64,17 @@ jobs:
         run: ssh $USER@$VPS_IP "cd $NEW_WORKING_FOLDER && NODE_ENV=production npm run build"  # Build the application using npm on the VPS
 
      
-
       - name: Stop application with PM2 (if running)
-        run:  |
-          ssh $USER@$VPS_IP "
-          npx pm2 list | grep -q '${{ env.APP_NAME }}'
-          if [ $? -eq 0 ]; then  # Check if the exit status ($?) is 0
-            npx pm2 stop '${{ env.APP_NAME }}';
-            echo 'Process ${{ env.APP_NAME }} stopped.';
-          else
-            echo 'Process ${{ env.APP_NAME }} not found, skipping stop command.';
-          fi
-          "
+        run: |
+          ssh "$USER@$VPS_IP" '
+            npx pm2 list | grep -qiw "${{ env.APP_NAME }}" # added iw for better matching
+            if [ $? -eq 0 ]; then
+              npx pm2 stop "${{ env.APP_NAME }}"
+              echo "Process ${{ env.APP_NAME }} stopped."
+            else
+              echo "Process ${{ env.APP_NAME }} not found, skipping stop command."
+            fi
+          '
 
 
       - name: Move WORKING_FOLDER to OLD_WORKING_FOLDER
@@ -88,10 +87,11 @@ jobs:
         run: ssh $USER@$VPS_IP "mv $NEW_WORKING_FOLDER $WORKING_FOLDER"  # Move the new working folder to the working folder on the VPS
 
       - name: Restart application with PM2
-        run: | 
+        run: |
           ssh $USER@$VPS_IP "
             cd $WORKING_FOLDER
-            if npx pm2 list | grep -q '${{ env.APP_NAME }}'; then
+            npx pm2 list | grep -qiw '${{ env.APP_NAME }}' # added iw for better matching
+            if [ $? -eq 0 ]; then
               npx pm2 restart '${{ env.APP_NAME }}';
             else
               npx pm2 start npm --name '${{ env.APP_NAME }}' -- run start;
@@ -99,14 +99,4 @@ jobs:
             npx pm2 save --force
           "
 
-      # - name: Restart application with PM2
-      #   run: | 
-      #     ssh $USER@$VPS_IP "
-      #       if npx pm2 list | grep -q '${{ env.APP_NAME }}'; then
-      #         npx pm2 restart '${{ env.APP_NAME }}';
-      #       else
-      #         npx pm2 start npm --name '${{ env.APP_NAME }}' -- run start;
-      #       fi
-      #       npx pm2 save
-      #     "
 
