add else if pm2 not started

diff --git a/.github/workflows/simple-ci-cd.yml b/.github/workflows/simple-ci-cd.yml
--- a/.github/workflows/simple-ci-cd.yml
+++ b/.github/workflows/simple-ci-cd.yml
@@ -63,14 +63,26 @@ jobs:
         run: ssh $USER@$VPS_IP "cd $NEW_WORKING_FOLDER && NODE_ENV=production npm run build"  # Build the application using npm on the VPS
 
       - name: Stop application with PM2 (if running)
-        run: |
+        run:  |
           ssh $USER@$VPS_IP "
-            if npx pm2 list | grep -q '${{ env.APP_NAME }}'; then
-              npx pm2 stop '${{ env.APP_NAME }}';
-            else
-              echo 'Process ${{ env.APP_NAME }} not found, skipping stop command.';
-            fi
+          pm2 list | grep -q '${{ env.APP_NAME }}'
+          if [ $? -eq 0 ]; then  # Check if the exit status ($?) is 0
+            pm2 stop '${{ env.APP_NAME }}';
+            echo 'Process ${{ env.APP_NAME }} stopped.';
+          else
+            echo 'Process ${{ env.APP_NAME }} not found, skipping stop command.';
+          fi
           "
+
+      # - name: Stop application with PM2 (if running)
+      #   run: |
+      #     ssh $USER@$VPS_IP "
+      #       if npx pm2 list | grep -q '${{ env.APP_NAME }}'; then
+      #         npx pm2 stop '${{ env.APP_NAME }}';
+      #       else
+      #         echo 'Process ${{ env.APP_NAME }} not found, skipping stop command.';
+      #       fi
+      #     "
 
       - name: Move WORKING_FOLDER to OLD_WORKING_FOLDER
         run: ssh $USER@$VPS_IP "
